#!/bin/bash 

STT=0
CNT=0

local_ext_file="$HOME/.config/whats"
ext_file=mapped_link

map_ext_link="$local_ext_file/$ext_file"

[ ! -d "$local_ext_file" ] && mkdir "$local_ext_file"

while :; do
  L1="$(md5sum <<< "$(xclip -o)")"
  [ "$STT" = 1 ] && {
    [ "$L1" != "$L2" ] && {
      check_link=$(xclip -o)
      [ "${check_link::8}" == "https://" ] && {
        echo "$check_link" > "$map_ext_link"
      }
      [ "${check_link::7}" == "http://" ] && {
        echo "$check_link" > "$map_ext_link"
      }
    }
  }

  [ -f "$map_ext_link" ] && {
    # shellcheck disable=SC2015
    [ "$CNT" -lt 10 ] && {
      CNT=$((CNT + 1))
    } || {
      rm -r "$map_ext_link"
      CNT=0
    }
  }

  STT=1; L2=$L1
  sleep 1
done
